language: node_js
node_js:
  - "8.12.0"
cache:
  directories:
    - node_modules
before_install:
  - npm config set shrinkwrap false
  - npm install -g @vue/cli
install:
  -  npm install
script:
  - npm run build